version: '3'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data:rw

    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  php-fpm:
    image: php:8.0-fpm
    build:
      context: ./docker/php-fpm
      <<: *app-cache-from
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./api:/var/www/
      
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./api:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
