parameters:
    # ...
    env(ELASTICSEARCH_HOST): 'http://localhost:9200'
api_platform:
    title: The Resealer API
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    defaults:
        pagination_enabled: true
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
             apiKey:
                name: Authorization
                type: header
    eager_loading:
        force_eager: false
